nodeLinker: node-modules

# Add the supportedArchitectures property
supportedArchitectures:
  - 'x64'  # Add the architecture for the current platform
  - 'arm64'  # Add the architecture for the other platform
